# Generated by Django 5.0.6 on 2024-10-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ALumnos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("n_reticulate", models.IntegerField()),
                ("semester", models.IntegerField()),
                ("career", models.CharField()),
                ("RFID", models.CharField(unique=True)),
            ],
        ),
    ]
